# Generated by Django 4.1.5 on 2023-03-10 05:29

import Ttrail.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=254, unique=True)),
                ('Ver_code', models.CharField(blank=True, default='', max_length=254)),
                ('Create_datetime', models.DateTimeField(auto_now_add=True)),
                ('Status', django_enumfield.db.fields.EnumField(default=2, enum=Ttrail.models.Admin.STATUS_user)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
